apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['service', 'alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'webhook-notifications'
      routes:
        - match:
            severity: critical
          receiver: 'webhook-notifications'
          continue: true

    receivers:
      - name: 'webhook-notifications'
        webhook_configs:
          - url: 'http://host.minikube.internal:3000/api/alerts/webhook'
            send_resolved: true 